Improve/options page
scombz-utilities/scombz-utilities-react pull request #50
Opened 2024-05-13 16:22 UTC by newt239

既に差分が大きいのでこのPRではここまでで区切ります、すみません......。

## 概要

- 設定の変更が即座に保存されるよう変更（同時にスナックバーを表示）
- 横幅を1000pxに制限し、詳細設定への切り替えボタンを画面上部に移動
- ReactのuseIdフックを使い、すべてのlabelタグにfor属性を付与
- `Custom{Select, Switch, TextField, RemovableList}.tsx`コンポーネントにおける、i18nテキストを取得するための冗長な記述のリファクタ
- 幾つかの設定項目の文言

## スクリーンショット（変更の場合は変更前と変更後が分かるように）

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [ ] NO

## チェック項目

- [ ] ビルドが通る
- [ ] lintが通る
- [ ] 作成した機能がDev環境で想定通りに動作する
- [ ] 作成した機能がビルド環境で想定通りに動作する
- [ ] 複雑なコードにはコメントを記載してある

### 種別

- optimisation - 既存機能修正・最適化
- style - スタイル変更

2024-05-13 16:50 UTC, yudai1204 requested changes
大まかには良さそうです！
3点だけ気になった点を書きました！！
ありがとうございます！！！

2024-05-13 16:50 UTC, yudai1204 commented on src/options/components/CustomContainerParent.tsx
> -        </Typography>
ここの部分を残して欲しいです！
理由としては、設定画面からIO機能でエクスポートした際などに、jsonファイルのキーがわかるようにしたいためです

2024-05-13 16:50 UTC, yudai1204 commented on src/options/components/CustomTextField.tsx
> +        onChange={onChange}
ここなんですが、reactの`onChange`が通常の`onInput`と同じ挙動をするため入力時に常にsnackbarが表示されるのが気になりました
`onBlur`で取る方が良さそうかも

2024-05-13 16:50 UTC, yudai1204 commented on src/options/index.tsx
> -              </Button>
現状カスタムCSSのみしか存在しませんが、マルチラインのTextFieldやTextAreaの場合は保存ボタンないし `onBlur` がUX的に良さそうな気がします

2024-05-13 21:27 UTC, newt239 commented on src/options/components/CustomTextField.tsx
> +        onChange={onChange}
ですよね、ちょっと気になっていた
onBlurも良さそうですがそのままタブ切り替えされるとつらいので、ここは素直に保存ボタンつけちゃおうと思います！

2024-05-14 06:32 UTC, yudai1204 requested changes
良さそうです！
申し訳ないんですが、カスタムCSSだけ保存ボタンを出すように修正お願いしたいです！
(onChangeで発火してそう)

↓ここです

https://github.com/scombz-utilities/scombz-utilities-react/blob/1ef5b3ddfc3a207fac1c6475966d83416382c80c/src/options/components/CustomCSS.tsx#L15

2024-05-14 06:36 UTC, newt239 commented
あ、ごめんなさい意味を理解してませんでした🙏
了解です！今直します！

2024-05-14 07:06 UTC, yudai1204 approved these changes
![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F22f76ebb-1aca-4625-b3bd-288834f91953.jpg%3Fh%3Dd1cb525d%26itok%3De97BdT_B?alt=media&token=46fed25b-edde-4bf4-97a2-d715ed970a9e)

2024-05-14 07:15 UTC, merged