Improve/options tab
scombz-utilities/scombz-utilities-react pull request #52
Opened 2024-05-16 11:16 UTC by newt239

## 概要

### タブごとにURL paramsを切り替えてパスが切り替わるよう変更

デバッグのとき毎回戻っちゃうのが辛くていっそページを分けてみましたが、SPAにはできないので毎回画面がちらつくという問題があるので一長一短かも

### 設定項目を以下のように分類し、再配置しました
- 基本設定
  - シラバス連携
  - 自動ログイン
- ウィジェット設定
  - 時間割ウィジェット
  - 課題表示ウィジェット
  - カスタムウィジェット
- 詳細設定
  - 科目ページ
  - 課題提出ページ
  - LMSページ
  - 科目別ページ
  - レイアウト変更
  - その他

各分類内での順番は、別PRで設定説明文の改善＆i18nと一緒に出そうと思っています。分類方法についてより分かりやすい提案があればお願いします🙇‍♂️ (個人的にはレイアウト変更を独立したタブにするのもありかな、と思っています)

## スクリーンショット（変更の場合は変更前と変更後が分かるように）

### 変更前

### 変更後

| 基本設定 | ウィジェット設定 | 詳細設定 |
| ---- | ---- | ---- |
| ![chrome-extension___gokpobalgmodinoadfkjpnjfkhamfhmo_options html_tab=basic](https://github.com/scombz-utilities/scombz-utilities-react/assets/51036153/764ebeb5-b449-4cfa-8ff3-e36d12fa4e22) | ![chrome-extension___gokpobalgmodinoadfkjpnjfkhamfhmo_options html_tab=widget](https://github.com/scombz-utilities/scombz-utilities-react/assets/51036153/58390910-f7e7-4ccf-a578-7ae706f65c1c) | ![chrome-extension___gokpobalgmodinoadfkjpnjfkhamfhmo_options html_tab=advanced](https://github.com/scombz-utilities/scombz-utilities-react/assets/51036153/7ff64608-78e8-43ce-8ffa-1e02a3016d9e) |

2024-05-16 13:26 UTC, yudai1204 requested changes
全体的には、良さそう👀
(もし設定が1つ消えていたとしても、わからないかも。newtくんを信じます！)

多分提案コードを元に見てもらえればタブ変更時にページ遷移はなくなりつついけると思うので、やってみて欲しいです！

2024-05-16 13:26 UTC, yudai1204 commented on src/options/index.tsx
> +            </Tabs>
Tabをanchorエレメントにするとページ遷移が生じてしまうので、 `history.pushState()` でurlを書き換えつつSPAを保持すると理想のUXを実現できそうです
以下、試してないので動くかわからないですが

```suggestion
            <Tabs variant="scrollable" scrollButtons="auto" value={currentTab || "basic"}
              onChange={(_, value) => {
                setCurrentTab(value);
                history.pushState(null, "", `?tab=${value}`);
              }}
            >
              <Tab value="basic" label="基本設定" />
              <Tab value="widget" label="ウィジェット設定" />
              <Tab value="advanced" label="詳細設定" />
              <Tab value="customcss" label="カスタムCSS" />
              <Tab value="data" label={chrome.i18n.getMessage("IOReset")} />
              <Tab value="info" label="情報" />
            </Tabs>
```

2024-05-16 13:26 UTC, yudai1204 commented on src/options/index.tsx
> +            </Tabs>
あ、↑だとsetCurrentTabがなさそうなのでuseStateにしてください💦

2024-05-16 23:58 UTC, newt239 commented on src/options/index.tsx
> +            </Tabs>
いい感じに動きました！ありがとうございます🙇‍♂️

2024-05-17 02:31 UTC, yudai1204 approved these changes
良さそう、ヨシ！
![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F2428b3ed-b36c-4c4b-bffb-b0695a7b67bc.jpg?alt=media&token=a22c0b69-c794-46ae-8e2b-7cb8d559f1c8)

2024-05-17 02:47 UTC, merged